CREATE TABLE item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT,
    condition VARCHAR(50) NOT NULL,
    category_id INTEGER,
    seller_id INTEGER NOT NULL
);

CREATE TABLE lot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    starting_price DECIMAL(9, 2) NOT NULL,
    minimum_bid_increment DECIMAL(9, 2) NOT NULL,
    auction_start TIMESTAMPTZ NOT NULL,
    auction_end TIMESTAMPTZ NOT NULL,
    winning_bid_id INTEGER DEFAULT NULL
);

CREATE TABLE category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE bid (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id INTEGER NOT NULL,
    bidder_id INTEGER NOT NULL,
    amount DECIMAL(9, 2) NOT NULL,
    time TIMESTAMPTZ NOT NULL,
    retracted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE purchase (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id INTEGER NOT NULL,
    amount DECIMAL(9, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    bank_account_number VARCHAR(100) NOT NULL
);

CREATE TABLE "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    address_id INTEGER NOT NULL
);

CREATE TABLE address (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address TEXT NOT NULL
);

CREATE TABLE "group" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE user_group (
    user_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, group_id)
);

ALTER TABLE item ADD CONSTRAINT fk_item_category FOREIGN KEY (category_id) REFERENCES category(id);
ALTER TABLE item ADD CONSTRAINT fk_item_user FOREIGN KEY (seller_id) REFERENCES "user"(id);
ALTER TABLE lot ADD CONSTRAINT fk_lot_item FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE lot ADD CONSTRAINT fk_lot_bid FOREIGN KEY (winning_bid_id) REFERENCES bid(id);
ALTER TABLE bid ADD CONSTRAINT fk_bid_lot FOREIGN KEY (lot_id) REFERENCES lot(id);
ALTER TABLE bid ADD CONSTRAINT fk_bid_user FOREIGN KEY (bidder_id) REFERENCES "user"(id);
ALTER TABLE purchase ADD CONSTRAINT fk_purchase_bid FOREIGN KEY (bid_id) REFERENCES bid(id);
ALTER TABLE "user" ADD CONSTRAINT fk_user_address FOREIGN KEY (address_id) REFERENCES address(id);
ALTER TABLE user_group ADD CONSTRAINT fk_user_group_user FOREIGN KEY (user_id) REFERENCES "user"(id);
ALTER TABLE user_group ADD CONSTRAINT fk_user_group_group FOREIGN KEY (group_id) REFERENCES "group"(id);
